on: push
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.13.0
        env:
          PAGES_BRANCH: build
          TOKEN: ${{ secrets.ZOLA_MFF }}
